### ISSUE TITLE
Apply without human position

### ISSUE THREAD

**Issue by NamCyan** [andvg3/LSDM#1]
Great work!
Can your method be applied to command without the present of human position. E.g. I want to Place a table in the left conner of the room and then place a chair near the table.

**Comment by andvg3** [comment]
Hi NamCyan,

Yes, there is a section "Ablation Study" in our paper, where we omit the presence of human. Our method can be applied to train generating furniture given the existing objects and text prompt.

Best regards,
An Vuong.
