### ISSUE TITLE
About HUMANISE dataset

### ISSUE THREAD

**Issue by iamyouno** [andvg3/LSDM#2]
Hi, I want to train with HUMANISE dataset, and I downloaded dataset from their web site. 
But it seems to have a different format.

In the code, it seems that data/humanise/objs, data/humanise/train are needed to create class HUMANISE(Dataset):. 
The humanise datsets I downloaded are in the format below.
|- HUMANISE/
    |- align_data_release/
    |- aling_data_v3/
    |- checkpoints/
    |- pure_motion/
    |- annotation.csv
    |- motions.zip
    |- readme.txt

Is there any preprocessing code for HUMANISE data or Can I get your preprocessed-HUMANISE data?

**Comment by andvg3** [comment]
Sure. If you or anyone want to access our utilized version of HUMANISE, please send an email to andvg3@gmail.com.

Best regards,
An Vuong

**Comment by iamyouno** [comment]
Thanks!

Can I get your utilized version of HUMANISE?

Best regards,
Younho Jeon

2024년 7월 24일 (수) 오후 8:27, An Vuong ***@***.***>님이 작성:
